version: '3.8'

services:
  api:
    build: .
    container_name: bookstore-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bookstore-network

  db:
    image: mysql:8.0
    container_name: bookstore-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bookstore-network

volumes:
  mysql_data:

networks:
  bookstore-network:
    driver: bridge